{% set name = "coolname" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coolname-{{ version }}.tar.gz
  sha256: 6c5d5731759104479e7ca195a9b64f7900ac5bead40183c09323c7d0be9e75c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - coolname
    - coolname.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alexanderlukanin13/coolname
  summary: Random name and slug generator
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vinisalazar
